### ISSUE TITLE
Stock Picking Barcode not displaying available lot

### ISSUE THREAD

**Issue by flotho** [itpp-labs/website-addons#148] opened 2017-01-17 20:23 UTC
Hi @yelizariev ,

Hope you're ding well. Best wishes.
Thanks for the port of the barcode interface.

I've tested it wit products that are managed by lot and expiry dates etc... In the UI, the lots are not displayed once you tried to choose the lot.
No special message is returned

**Comment by yelizariev** [comment] 2017-01-18 05:24
Hi @flotho, 
nice to see you again.

Do you mean 9.0 or 10.0? I made some update in 9.0, but haven't merged it to 10.0 yet.

If it's about 9.0, could describe the issue. @ilmir-k will try to reproduce it

**Comment by trojikman** [comment] 2020-02-24 14:56
We have not received any additional information for reproducing the error since 2017, so I close this issue

**Closed by trojikman** 2020-02-24 14:56 UTC
